CREATE TABLE IF NOT EXISTS `Campaigns`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `client_id` INT NOT NULL,
    `client_account_id` INT NOT NULL,
    `name` VARCHAR(80) NOT NULL,
    `desc` VARCHAR(80) NOT NULL,
    `ad_url` VARCHAR(80) NOT NULL,
    `target_age` INT,
    `target_gender` VARCHAR(80),
    `target_ethnicity` VARCHAR(80),
    `target_geo_location` VARCHAR(80),
    `target_disability` VARCHAR(80),
    `target_veteran` TINYINT,
    `total_views` INT NOT NULL DEFAULT 0,
    `reward_tokens` INT NOT NULL DEFAULT 10,
    `bonus_tokens` INT DEFAULT 0,
    `avg_happy` INT NOT NULL DEFAULT 0,
    `avg_disgust` INT NOT NULL DEFAULT 0,
    `avg_fear` INT NOT NULL DEFAULT 0,
    `avg_sad` INT NOT NULL DEFAULT 0,
    `avg_neutral` INT NOT NULL DEFAULT 0,
    `avg_surprise` INT NOT NULL DEFAULT 0,
    `last_name` VARCHAR(80) NOT NULL,
    `ends` VARCHAR(80) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP DEFAULT 0,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`client_id`) REFERENCES `Clients`(`id`),
    FOREIGN KEY (`client_account_id`) REFERENCES `ClientAccountData`(`id`)
)