CREATE TABLE IF NOT EXISTS `Prizes`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `img_url` VARCHAR(100) NOT NULL,
    `val_dol` INT NOT NULL,
    `val_cent` INT NOT NULL,
    `token_cost` INT NOT NULL,
    `redeem_code` INT NOT NULL,
    `stock` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP DEFAULT 0,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)